[tool.poetry]
name = "respec-analysis"
version = "0.1.0"
description = "Data analysis for the Re:spec project"
authors = ["Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>"]

[tool.poetry.dependencies]
python = "^3.7"
astropy = "^4.0"
numpy = "^1.18"
scipy = "^1.4"
jupyter-io = "^0.1.2"
matplotlib = "^3.1"
xarray = "^0.15.0"
pandas = "^1.0.1"
scikit-learn = "^0.22.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7"
ipython = "^7.11"
jupyter = "^1.0"
jupyterlab = "^1.2"
pytest = "^5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
